### ISSUE TITLE
Output File Visualization

### ISSUE THREAD

**Issue by Ezharjan** [b-safwat/sumo2vision#1]
Thanks for your nice work!
I followed your steps mentioned in `README` and finally still did not get any visual results but only the following content in the terminal after running `python sumo_visual_scenario.py`:
```
...
99985
99986
99987
99988
99989
99990
99991
99992
99993
99994
99995
99996
99997
99998
99999
100000
Simulation #2_0 terminated!
(sumo2vision) alex@fst-computer:~/Documents/sumo2vision$ 
```

**Are there any ways to visualize the result?**

**Comment by b-hakim** [comment]
Yes! For that you would need to set the following parameter to True:

> hyper_params['save_visual'] = True

You would need to rerun it though. Afterward, you should be able to see images saved for each scenario. The Field of View (FoV) for each vehicle shall be drawn and both the classical vehicles and the autonomous vehicles will have different colors. 

Note: Once it starts running, you can check the output dir and see the images without waiting for the program to finish generation. Also, there is a way to increase the quality/resolution of the image as needed but I think I did not make a hyperparam for that, let me know if that is needed.

**Comment by Ezharjan** [comment]
Thanks!
Running `python sumo_visual_scenario.py` after revising `hyper_params['save_visual']` to `True` did generate an image as follows, but it seems that the generated image looks like the semantic segmentation of the whole picture of the map.

![Screenshot from 2024-01-29 18-23-11](https://github.com/b-hakim/sumo2vision/assets/60126466/61a9bba6-576a-4daa-ad5c-d2ec36ab9875)


 
Is **generating the semantic segmentation of the map** what you mean by "Simulate perception sensors and object detection based on traffic data generated by Sumo. " in the `README`?  


Thanks!

**Comment by b-hakim** [comment]
It generated an image of the map including any geometric polygons in the map like buildings. If you have vehicles running at this frame, you should be able to see them (they might be too small to see). I would recommend trying a map for a small area first, for the sake of debugging, then scale up. If you know the location of the vehicles, you can also zoom in and see them. 

I guess you can also select a specific area of the road and save it for a suitable visualizing for your project. This can be done when saving the image (at [this ](https://github.com/b-hakim/sumo2vision/blob/ae2264b39907925c706130120df1e7edf2061ee3/sumo_visualizer.py#L129) line)

**Comment by Ezharjan** [comment]
> It generated an image of the map including any geometric polygons in the map like buildings. If you have vehicles running at this frame, you should be able to see them (they might be too small to see). I would recommend trying a map for a small area first, for the sake of debugging, then scale up. If you know the location of the vehicles, you can also zoom in and see them.
> 
> I guess you can also select a specific area of the road and save it for a suitable visualizing for your project. This can be done when saving the image (at [this ](https://github.com/b-hakim/sumo2vision/blob/ae2264b39907925c706130120df1e7edf2061ee3/sumo_visualizer.py#L129) line)

Thank you very much!
